
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */




/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */



/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */

Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext-more": "touch/src/core/Ext-more.js",
  "Ext.DomHelper": "touch/src/dom/Helper.js",
  "Ext.DomQuery": "touch/src/dom/Query.js",
  "Ext.Element-alignment": "touch/src/dom/Element.alignment.js",
  "Ext.Element-all": "touch/src/dom/Element.traversal.js",
  "Ext.Element-insertion": "touch/src/dom/Element.insertion.js",
  "Ext.Element-position": "touch/src/dom/Element.position.js",
  "Ext.Element-static": "touch/src/dom/Element.static.js",
  "Ext.Element-style": "touch/src/dom/Element.style.js",
  "Ext.Element-traversal": "touch/src/dom/Element.traversal.js",
  "Ext.core.DomQuery": "touch/src/dom/Query.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.Entry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileEntry": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.filesystem.FileSystem": "touch/src/device/filesystem/Sencha.js",
  "Ext.device.purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "touch/src/draw/engine/SvgContext.js",
  "Ext.field.Div": "touch/src/ux/ColorPickerField.js",
  "book": "app",
  "book.view.book.AnnotationMenu": "app/view/book/AnnotationMenu.js",
  "book.view.book.CompileSubMenu": "app/view/book/CompileSubMenu.js",
  "book.view.book.DiscussMenu": "app/view/book/DiscussMenu.js",
  "book.view.book.ExtractMenu": "app/view/book/ExtractMenu.js",
  "book.view.book.ListItem": "app/view/book/ListItem.js",
  "book.view.book.LookupMenu": "app/view/book/LookupMenu.js",
  "book.view.book.MarkSubMenu": "app/view/book/MarkSubMenu.js",
  "book.view.book.NoteSubMenu": "app/view/book/NoteSubMenu.js",
  "book.view.book.SelectionMenu": "app/view/book/SelectionMenu.js",
  "book.view.book.ShareSubMenu": "app/view/book/ShareSubMenu.js",
  "book.view.book.TagSubMenu": "app/view/book/TagSubMenu.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.chart.AbstractChart": [],
  "Ext.chart.CartesianChart": [
    "Ext.chart.Chart"
  ],
  "Ext.chart.Legend": [],
  "Ext.chart.MarkerHolder": [],
  "Ext.chart.Markers": [],
  "Ext.chart.PolarChart": [],
  "Ext.chart.SpaceFillingChart": [],
  "Ext.chart.axis.Axis": [],
  "Ext.chart.axis.Category": [],
  "Ext.chart.axis.Numeric": [],
  "Ext.chart.axis.Time": [],
  "Ext.chart.axis.layout.CombineDuplicate": [],
  "Ext.chart.axis.layout.Continuous": [],
  "Ext.chart.axis.layout.Discrete": [],
  "Ext.chart.axis.layout.Layout": [],
  "Ext.chart.axis.segmenter.Names": [],
  "Ext.chart.axis.segmenter.Numeric": [],
  "Ext.chart.axis.segmenter.Segmenter": [],
  "Ext.chart.axis.segmenter.Time": [],
  "Ext.chart.axis.sprite.Axis": [],
  "Ext.chart.grid.CircularGrid": [],
  "Ext.chart.grid.HorizontalGrid": [],
  "Ext.chart.grid.RadialGrid": [],
  "Ext.chart.grid.VerticalGrid": [],
  "Ext.chart.interactions.Abstract": [],
  "Ext.chart.interactions.CrossZoom": [],
  "Ext.chart.interactions.Crosshair": [],
  "Ext.chart.interactions.ItemHighlight": [],
  "Ext.chart.interactions.ItemInfo": [],
  "Ext.chart.interactions.PanZoom": [],
  "Ext.chart.interactions.Rotate": [],
  "Ext.chart.interactions.RotatePie3D": [],
  "Ext.chart.label.Callout": [],
  "Ext.chart.label.Label": [],
  "Ext.chart.series.Area": [],
  "Ext.chart.series.Bar": [],
  "Ext.chart.series.CandleStick": [],
  "Ext.chart.series.Cartesian": [],
  "Ext.chart.series.Gauge": [],
  "Ext.chart.series.ItemPublisher": [],
  "Ext.chart.series.Line": [],
  "Ext.chart.series.Pie": [],
  "Ext.chart.series.Pie3D": [],
  "Ext.chart.series.Polar": [],
  "Ext.chart.series.Radar": [],
  "Ext.chart.series.Scatter": [],
  "Ext.chart.series.Series": [],
  "Ext.chart.series.StackedCartesian": [],
  "Ext.chart.series.sprite.Aggregative": [],
  "Ext.chart.series.sprite.Area": [],
  "Ext.chart.series.sprite.Bar": [],
  "Ext.chart.series.sprite.CandleStick": [],
  "Ext.chart.series.sprite.Cartesian": [],
  "Ext.chart.series.sprite.Line": [],
  "Ext.chart.series.sprite.Pie3DPart": [],
  "Ext.chart.series.sprite.PieSlice": [],
  "Ext.chart.series.sprite.Polar": [],
  "Ext.chart.series.sprite.Radar": [],
  "Ext.chart.series.sprite.Scatter": [],
  "Ext.chart.series.sprite.StackedCartesian": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.draw.Animator": [],
  "Ext.draw.Color": [],
  "Ext.draw.Component": [],
  "Ext.draw.Draw": [],
  "Ext.draw.Group": [],
  "Ext.draw.LimitedCache": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Path": [],
  "Ext.draw.SegmentTree": [],
  "Ext.draw.Solver": [],
  "Ext.draw.Surface": [],
  "Ext.draw.TextMeasurer": [],
  "Ext.draw.TimingFunctions": [],
  "Ext.draw.engine.Canvas": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgContext": [],
  "Ext.draw.engine.SvgContext.Gradient": [],
  "Ext.draw.engine.SvgExporter": [],
  "Ext.draw.gradient.Gradient": [],
  "Ext.draw.gradient.Linear": [],
  "Ext.draw.gradient.Radial": [],
  "Ext.draw.modifier.Animation": [],
  "Ext.draw.modifier.Highlight": [],
  "Ext.draw.modifier.Modifier": [],
  "Ext.draw.modifier.Target": [],
  "Ext.draw.sprite.AnimationParser": [],
  "Ext.draw.sprite.Arc": [],
  "Ext.draw.sprite.AttributeDefinition": [],
  "Ext.draw.sprite.AttributeParser": [],
  "Ext.draw.sprite.Circle": [],
  "Ext.draw.sprite.Composite": [],
  "Ext.draw.sprite.Ellipse": [],
  "Ext.draw.sprite.EllipticalArc": [],
  "Ext.draw.sprite.GradientDefinition": [],
  "Ext.draw.sprite.Image": [],
  "Ext.draw.sprite.Instancing": [],
  "Ext.draw.sprite.Line": [],
  "Ext.draw.sprite.Path": [],
  "Ext.draw.sprite.Rect": [],
  "Ext.draw.sprite.Sector": [],
  "Ext.draw.sprite.Sprite": [],
  "Ext.draw.sprite.Text": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Div": [],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.grid.Grid": [],
  "Ext.grid.Row": [],
  "Ext.grid.column.Column": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.BufferedList": [],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.AccordionList": [
    "Ext.AccordionList"
  ],
  "Ext.ux.AccordionListItem": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.AudioPlayer": [],
  "Ext.ux.ColorPickerField": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.Iframe": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "book.controller.BookController": [],
  "book.controller.BookRoutesController": [],
  "book.controller.BookTimer": [],
  "book.model.MBookInfoTab": [],
  "book.model.MBookSlider": [],
  "book.model.MCategoryAccordionList": [],
  "book.model.MDiscussMenu": [],
  "book.model.MListSelecrSearchResult": [],
  "book.model.MOwnedBookList": [],
  "book.model.MReadBookPageList": [],
  "book.model.MSearchScreen": [],
  "book.model.MSettingAccordionList": [],
  "book.store.SBookInfoTab": [],
  "book.store.SBookSlider": [],
  "book.store.SCategoryAccordionList": [],
  "book.store.SDiscussMenu": [],
  "book.store.SListSelecrSearchResult": [],
  "book.store.SOwnedBookList": [],
  "book.store.SReadBookPageList": [],
  "book.store.SSearchScreen": [],
  "book.store.SSettingAccordionList": [],
  "book.ux.PanelAction": [],
  "book.view.AddBookView": [],
  "book.view.AudioPlayer": [],
  "book.view.BookSlider": [],
  "book.view.BookSliderContainer": [],
  "book.view.BookSliderItem": [],
  "book.view.BookTitlebar": [],
  "book.view.CategoryAccordionList": [],
  "book.view.CategoryListContainer": [],
  "book.view.CategoryMainContainer": [],
  "book.view.ColorPicker": [],
  "book.view.CurrentBookPopUp": [],
  "book.view.LibrarybyLanguage": [],
  "book.view.ListPopUp": [],
  "book.view.ListSelecrSearchResult": [],
  "book.view.ListSelecrSearchResultContainer": [],
  "book.view.Main": [],
  "book.view.MainBookContainer": [],
  "book.view.MainContainer": [],
  "book.view.MainNavigation": [],
  "book.view.OwnedBookEconomicsList": [],
  "book.view.OwnedBookHistoryList": [],
  "book.view.OwnedBookList": [],
  "book.view.ReadBookPageList": [],
  "book.view.RecentlyReadTitle": [],
  "book.view.RightCategoryTitle": [],
  "book.view.RightSidebarContainer": [],
  "book.view.SearchBooksView": [],
  "book.view.SettingAccordionList": [],
  "book.view.TabPanel": [],
  "book.view.TopSearchField": [],
  "book.view.TopSettingPopUp": [],
  "book.view.VideoPlayer": [],
  "book.view.audiovideo.AudioVideoLecture": [],
  "book.view.audiovideo.AudioVideoLectureContainer": [],
  "book.view.book.AnnotationMenu": [],
  "book.view.book.CompileSubMenu": [],
  "book.view.book.DiscussMenu": [],
  "book.view.book.ExtractMenu": [],
  "book.view.book.ListItem": [],
  "book.view.book.LookupMenu": [],
  "book.view.book.MarkSubMenu": [],
  "book.view.book.NoteSubMenu": [],
  "book.view.book.SelectionMenu": [],
  "book.view.book.ShareSubMenu": [],
  "book.view.book.TagSubMenu": [],
  "book.view.bookinfoscreen.BookInfoTab": [],
  "book.view.bookinfoscreen.BookInformationScreen": [],
  "book.view.bookinfoscreen.BookmarkTab": [],
  "book.view.bookinfoscreen.ColoredHighlightsTab": [],
  "book.view.bookinfoscreen.NamedTagsTab": [],
  "book.view.bookinfoscreen.NotesTab": [],
  "book.view.bookinfoscreen.ParagraphSummariesTab": [],
  "book.view.exerciseindicator.AssessmentQuizExercise": [],
  "book.view.exerciseindicator.AssessmentQuizExerciseContainer": [],
  "book.view.exerciseindicator.DiscussionQueExercise": [],
  "book.view.exerciseindicator.DiscussionQueExerciseContainer": [],
  "book.view.exerciseindicator.MemorizationAssignment": [],
  "book.view.exerciseindicator.MemorizationAssignmentContainer": [],
  "book.view.journal.JournalingAssignment": [],
  "book.view.journal.JournalingAssignmentContainer": [],
  "book.view.journal.MicroJournaling": [],
  "book.view.journal.MicroJournalingContainer": [],
  "book.view.memorization.MemorizationDeck": [],
  "book.view.memorization.MemorizationDeckContainer": [],
  "book.view.memorization.MemorizationEnginePopupDrillingScreen": [],
  "book.view.memorization.MemorizationEnginePopupDrillingScreenContainer": [],
  "book.view.quizscreen.AssessmentQuiz": [],
  "book.view.quizscreen.AssessmentQuizContainer": [],
  "book.view.studybar.CompletedStudeyProjectList": [],
  "book.view.studybar.CurrentOpenStudeyProjectList": [],
  "book.view.studybar.CurrentStudyProjectPopUp": [],
  "book.view.studybar.MembersLinkList": [],
  "book.view.studybar.ReadingConfigOptionsPopUp": [],
  "book.view.studybar.StudyProjectInfoScreen": [],
  "book.view.studybar.StudyProjectNavBar": [],
  "book.view.vocabularyassessment.VocabularyAssessment": [],
  "book.view.vocabularyassessment.VocabularyAssessmentContainer": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.chart.AbstractChart": [],
  "Ext.chart.CartesianChart": [
    "Ext.chart.Chart",
    "widget.chart"
  ],
  "Ext.chart.Legend": [
    "widget.legend"
  ],
  "Ext.chart.MarkerHolder": [],
  "Ext.chart.Markers": [],
  "Ext.chart.PolarChart": [
    "widget.polar"
  ],
  "Ext.chart.SpaceFillingChart": [
    "widget.spacefilling"
  ],
  "Ext.chart.axis.Axis": [
    "widget.axis"
  ],
  "Ext.chart.axis.Category": [
    "axis.category"
  ],
  "Ext.chart.axis.Numeric": [
    "axis.numeric"
  ],
  "Ext.chart.axis.Time": [
    "axis.time"
  ],
  "Ext.chart.axis.layout.CombineDuplicate": [
    "axisLayout.combineDuplicate"
  ],
  "Ext.chart.axis.layout.Continuous": [
    "axisLayout.continuous"
  ],
  "Ext.chart.axis.layout.Discrete": [
    "axisLayout.discrete"
  ],
  "Ext.chart.axis.layout.Layout": [],
  "Ext.chart.axis.segmenter.Names": [
    "segmenter.names"
  ],
  "Ext.chart.axis.segmenter.Numeric": [
    "segmenter.numeric"
  ],
  "Ext.chart.axis.segmenter.Segmenter": [],
  "Ext.chart.axis.segmenter.Time": [
    "segmenter.time"
  ],
  "Ext.chart.axis.sprite.Axis": [],
  "Ext.chart.grid.CircularGrid": [
    "grid.circular"
  ],
  "Ext.chart.grid.HorizontalGrid": [
    "grid.horizontal"
  ],
  "Ext.chart.grid.RadialGrid": [
    "grid.radial"
  ],
  "Ext.chart.grid.VerticalGrid": [
    "grid.vertical"
  ],
  "Ext.chart.interactions.Abstract": [
    "widget.interaction"
  ],
  "Ext.chart.interactions.CrossZoom": [
    "interaction.crosszoom"
  ],
  "Ext.chart.interactions.Crosshair": [
    "interaction.crosshair"
  ],
  "Ext.chart.interactions.ItemHighlight": [
    "interaction.itemhighlight"
  ],
  "Ext.chart.interactions.ItemInfo": [
    "interaction.iteminfo"
  ],
  "Ext.chart.interactions.PanZoom": [
    "interaction.panzoom"
  ],
  "Ext.chart.interactions.Rotate": [
    "interaction.rotate"
  ],
  "Ext.chart.interactions.RotatePie3D": [
    "interaction.rotatePie3d"
  ],
  "Ext.chart.label.Callout": [],
  "Ext.chart.label.Label": [],
  "Ext.chart.series.Area": [
    "series.area"
  ],
  "Ext.chart.series.Bar": [
    "series.bar"
  ],
  "Ext.chart.series.CandleStick": [
    "series.candlestick"
  ],
  "Ext.chart.series.Cartesian": [],
  "Ext.chart.series.Gauge": [
    "series.gauge"
  ],
  "Ext.chart.series.ItemPublisher": [],
  "Ext.chart.series.Line": [
    "series.line"
  ],
  "Ext.chart.series.Pie": [
    "series.pie"
  ],
  "Ext.chart.series.Pie3D": [
    "series.pie3d"
  ],
  "Ext.chart.series.Polar": [],
  "Ext.chart.series.Radar": [
    "series.radar"
  ],
  "Ext.chart.series.Scatter": [
    "series.scatter"
  ],
  "Ext.chart.series.Series": [],
  "Ext.chart.series.StackedCartesian": [],
  "Ext.chart.series.sprite.Aggregative": [],
  "Ext.chart.series.sprite.Area": [
    "sprite.areaSeries"
  ],
  "Ext.chart.series.sprite.Bar": [
    "sprite.barSeries"
  ],
  "Ext.chart.series.sprite.CandleStick": [
    "sprite.candlestickSeries"
  ],
  "Ext.chart.series.sprite.Cartesian": [],
  "Ext.chart.series.sprite.Line": [
    "sprite.lineSeries"
  ],
  "Ext.chart.series.sprite.Pie3DPart": [
    "sprite.pie3dPart"
  ],
  "Ext.chart.series.sprite.PieSlice": [
    "sprite.pieslice"
  ],
  "Ext.chart.series.sprite.Polar": [],
  "Ext.chart.series.sprite.Radar": [
    "sprite.radar"
  ],
  "Ext.chart.series.sprite.Scatter": [
    "sprite.scatterSeries"
  ],
  "Ext.chart.series.sprite.StackedCartesian": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.draw.Animator": [],
  "Ext.draw.Color": [],
  "Ext.draw.Component": [
    "widget.draw"
  ],
  "Ext.draw.Draw": [],
  "Ext.draw.Group": [],
  "Ext.draw.LimitedCache": [],
  "Ext.draw.Matrix": [],
  "Ext.draw.Path": [],
  "Ext.draw.SegmentTree": [],
  "Ext.draw.Solver": [],
  "Ext.draw.Surface": [
    "widget.surface"
  ],
  "Ext.draw.TextMeasurer": [],
  "Ext.draw.TimingFunctions": [],
  "Ext.draw.engine.Canvas": [],
  "Ext.draw.engine.Svg": [],
  "Ext.draw.engine.SvgContext": [],
  "Ext.draw.engine.SvgContext.Gradient": [],
  "Ext.draw.engine.SvgExporter": [],
  "Ext.draw.gradient.Gradient": [],
  "Ext.draw.gradient.Linear": [],
  "Ext.draw.gradient.Radial": [],
  "Ext.draw.modifier.Animation": [
    "modifier.animation"
  ],
  "Ext.draw.modifier.Highlight": [
    "modifier.highlight"
  ],
  "Ext.draw.modifier.Modifier": [],
  "Ext.draw.modifier.Target": [
    "modifier.target"
  ],
  "Ext.draw.sprite.AnimationParser": [],
  "Ext.draw.sprite.Arc": [
    "sprite.arc"
  ],
  "Ext.draw.sprite.AttributeDefinition": [],
  "Ext.draw.sprite.AttributeParser": [],
  "Ext.draw.sprite.Circle": [
    "sprite.circle"
  ],
  "Ext.draw.sprite.Composite": [
    "sprite.composite"
  ],
  "Ext.draw.sprite.Ellipse": [
    "sprite.ellipse"
  ],
  "Ext.draw.sprite.EllipticalArc": [
    "sprite.ellipticalArc"
  ],
  "Ext.draw.sprite.GradientDefinition": [],
  "Ext.draw.sprite.Image": [
    "sprite.image"
  ],
  "Ext.draw.sprite.Instancing": [
    "sprite.instancing"
  ],
  "Ext.draw.sprite.Line": [
    "sprite.line"
  ],
  "Ext.draw.sprite.Path": [
    "sprite.path"
  ],
  "Ext.draw.sprite.Rect": [
    "sprite.rect"
  ],
  "Ext.draw.sprite.Sector": [
    "sprite.sector"
  ],
  "Ext.draw.sprite.Sprite": [
    "sprite.sprite"
  ],
  "Ext.draw.sprite.Text": [
    "sprite.text"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Div": [
    "widget.div"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.grid.Grid": [
    "widget.grid"
  ],
  "Ext.grid.Row": [
    "widget.gridrow"
  ],
  "Ext.grid.column.Column": [
    "widget.column"
  ],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.BufferedList": [
    "plugin.bufferedlist"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.AccordionList": [
    "widget.accordionlist"
  ],
  "Ext.ux.AccordionListItem": [
    "widget.accordionlistitem"
  ],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.AudioPlayer": [
    "widget.audioplayer"
  ],
  "Ext.ux.ColorPickerField": [
    "widget.colorpickerfield"
  ],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.Iframe": [
    "widget.iframe"
  ],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "book.controller.BookController": [],
  "book.controller.BookRoutesController": [],
  "book.controller.BookTimer": [],
  "book.model.MBookInfoTab": [],
  "book.model.MBookSlider": [],
  "book.model.MCategoryAccordionList": [],
  "book.model.MDiscussMenu": [],
  "book.model.MListSelecrSearchResult": [],
  "book.model.MOwnedBookList": [],
  "book.model.MReadBookPageList": [],
  "book.model.MSearchScreen": [],
  "book.model.MSettingAccordionList": [],
  "book.store.SBookInfoTab": [],
  "book.store.SBookSlider": [],
  "book.store.SCategoryAccordionList": [],
  "book.store.SDiscussMenu": [],
  "book.store.SListSelecrSearchResult": [],
  "book.store.SOwnedBookList": [],
  "book.store.SReadBookPageList": [],
  "book.store.SSearchScreen": [],
  "book.store.SSettingAccordionList": [],
  "book.ux.PanelAction": [],
  "book.view.AddBookView": [
    "widget.addbookview"
  ],
  "book.view.AudioPlayer": [
    "widget.audioplayerview"
  ],
  "book.view.BookSlider": [
    "widget.bookslider"
  ],
  "book.view.BookSliderContainer": [
    "widget.bookslidercontainer"
  ],
  "book.view.BookSliderItem": [
    "widget.bookslideritem"
  ],
  "book.view.BookTitlebar": [
    "widget.booktitlebar"
  ],
  "book.view.CategoryAccordionList": [
    "widget.categoryaccordionlist"
  ],
  "book.view.CategoryListContainer": [
    "widget.categorylistcontainer"
  ],
  "book.view.CategoryMainContainer": [
    "widget.categorymaincontainer"
  ],
  "book.view.ColorPicker": [
    "widget.colorpicker"
  ],
  "book.view.CurrentBookPopUp": [
    "widget.currentbookpopup"
  ],
  "book.view.LibrarybyLanguage": [
    "widget.librarybylanguage"
  ],
  "book.view.ListPopUp": [
    "widget.listpopup"
  ],
  "book.view.ListSelecrSearchResult": [
    "widget.listselecrsearchresult"
  ],
  "book.view.ListSelecrSearchResultContainer": [
    "widget.listselecrsearchresultcontainer"
  ],
  "book.view.Main": [
    "widget.main"
  ],
  "book.view.MainBookContainer": [
    "widget.mainbookcontainer"
  ],
  "book.view.MainContainer": [
    "widget.maincontainer"
  ],
  "book.view.MainNavigation": [
    "widget.mainnavigation"
  ],
  "book.view.OwnedBookEconomicsList": [
    "widget.ownedbookeconomicslist"
  ],
  "book.view.OwnedBookHistoryList": [
    "widget.ownedbookhistorylist"
  ],
  "book.view.OwnedBookList": [
    "widget.ownedbooklist"
  ],
  "book.view.ReadBookPageList": [
    "widget.readbookpagelist"
  ],
  "book.view.RecentlyReadTitle": [
    "widget.recentlyreadtitle"
  ],
  "book.view.RightCategoryTitle": [
    "widget.rightcategorytitle"
  ],
  "book.view.RightSidebarContainer": [
    "widget.rightsidebarcontainer"
  ],
  "book.view.SearchBooksView": [
    "widget.searchbooksview"
  ],
  "book.view.SettingAccordionList": [
    "widget.settingaccordionlist"
  ],
  "book.view.TabPanel": [
    "widget.tabpanel"
  ],
  "book.view.TopSearchField": [
    "widget.topsearchfield"
  ],
  "book.view.TopSettingPopUp": [
    "widget.topsettingpopup"
  ],
  "book.view.VideoPlayer": [
    "widget.videoplayer"
  ],
  "book.view.audiovideo.AudioVideoLecture": [
    "widget.audiovideolecture"
  ],
  "book.view.audiovideo.AudioVideoLectureContainer": [
    "widget.audiovideolecturecontainer"
  ],
  "book.view.book.AnnotationMenu": [
    "widget.annotationmenu"
  ],
  "book.view.book.CompileSubMenu": [
    "widget.compilesubmenu"
  ],
  "book.view.book.DiscussMenu": [
    "widget.discussmenu"
  ],
  "book.view.book.ExtractMenu": [
    "widget.extractmenu"
  ],
  "book.view.book.ListItem": [
    "widget.examplelistitem"
  ],
  "book.view.book.LookupMenu": [
    "widget.lookupmenu"
  ],
  "book.view.book.MarkSubMenu": [
    "widget.marksubmenu"
  ],
  "book.view.book.NoteSubMenu": [
    "widget.notesubmenu"
  ],
  "book.view.book.SelectionMenu": [
    "widget.selectionmenu"
  ],
  "book.view.book.ShareSubMenu": [
    "widget.sharesubmenu"
  ],
  "book.view.book.TagSubMenu": [
    "widget.tagsubmenu"
  ],
  "book.view.bookinfoscreen.BookInfoTab": [
    "widget.bookinfotab"
  ],
  "book.view.bookinfoscreen.BookInformationScreen": [
    "widget.bookinformationscreen"
  ],
  "book.view.bookinfoscreen.BookmarkTab": [
    "widget.bookmarktab"
  ],
  "book.view.bookinfoscreen.ColoredHighlightsTab": [
    "widget.coloredhighlightstab"
  ],
  "book.view.bookinfoscreen.NamedTagsTab": [
    "widget.namedtagstab"
  ],
  "book.view.bookinfoscreen.NotesTab": [
    "widget.notestab"
  ],
  "book.view.bookinfoscreen.ParagraphSummariesTab": [
    "widget.paragraphsummariestab"
  ],
  "book.view.exerciseindicator.AssessmentQuizExercise": [
    "widget.assessmentquizexercise"
  ],
  "book.view.exerciseindicator.AssessmentQuizExerciseContainer": [
    "widget.assessmentquizexercisecontainer"
  ],
  "book.view.exerciseindicator.DiscussionQueExercise": [
    "widget.discussionqueexercise"
  ],
  "book.view.exerciseindicator.DiscussionQueExerciseContainer": [
    "widget.discussionqueexercisecontainer"
  ],
  "book.view.exerciseindicator.MemorizationAssignment": [
    "widget.memorizationassignment"
  ],
  "book.view.exerciseindicator.MemorizationAssignmentContainer": [
    "widget.memorizationassignmentcontainer"
  ],
  "book.view.journal.JournalingAssignment": [
    "widget.jaournalingassignment"
  ],
  "book.view.journal.JournalingAssignmentContainer": [
    "widget.jaournalingassignmentcontainer"
  ],
  "book.view.journal.MicroJournaling": [
    "widget.microjournaling"
  ],
  "book.view.journal.MicroJournalingContainer": [
    "widget.microjournalingcontainer"
  ],
  "book.view.memorization.MemorizationDeck": [
    "widget.memorizationdeck"
  ],
  "book.view.memorization.MemorizationDeckContainer": [
    "widget.memorizationdeckcontainer"
  ],
  "book.view.memorization.MemorizationEnginePopupDrillingScreen": [
    "widget.memorizationpopupdrillingscreen"
  ],
  "book.view.memorization.MemorizationEnginePopupDrillingScreenContainer": [
    "widget.memorizationpopupdrillingscreencontainer"
  ],
  "book.view.quizscreen.AssessmentQuiz": [
    "widget.assessmentquiz"
  ],
  "book.view.quizscreen.AssessmentQuizContainer": [
    "widget.assessmentquizcontainer"
  ],
  "book.view.studybar.CompletedStudeyProjectList": [
    "widget.completedstudeyprojectlist"
  ],
  "book.view.studybar.CurrentOpenStudeyProjectList": [
    "widget.currentppenstudeyprojectlist"
  ],
  "book.view.studybar.CurrentStudyProjectPopUp": [
    "widget.currentstudyprojectpopup"
  ],
  "book.view.studybar.MembersLinkList": [
    "widget.memberslinklist"
  ],
  "book.view.studybar.ReadingConfigOptionsPopUp": [
    "widget.readingconfigpptionspopup"
  ],
  "book.view.studybar.StudyProjectInfoScreen": [
    "widget.studyprojectinfoscreen"
  ],
  "book.view.studybar.StudyProjectNavBar": [
    "widget.studyprojectnavbar"
  ],
  "book.view.vocabularyassessment.VocabularyAssessment": [
    "widget.vocabularyassessment"
  ],
  "book.view.vocabularyassessment.VocabularyAssessmentContainer": [
    "widget.vocabularyassessmentContainer"
  ]
});


/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */




